name: gallery_picker
description: Gallery Picker is a flutter package that will allow you to pick media file(s), manage and navigate inside your gallery with modern tools and views.
version: 0.5.1
homepage: https://github.com/FlutterWay/gallery_picker
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  photo_gallery:
    path: ../photo_gallery
  permission_handler: ^12.0.1
  transparent_image: ^2.0.1
  video_player: ^2.10.0
  device_info_plus: ^11.5.0
  get: ^4.7.2
  video_thumbnail:
    git:
      url: https://github.com/Shahidbangash/video_thumbnail.git
  intl: ^0.20.2
  page_transition: ^2.2.1
  bottom_sheet_scaffold: ^0.1.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
